### ISSUE TITLE
ProtobufJS Error invalid wire type 4 at offset 1

### ISSUE THREAD

**Issue by jpshugrue** [jpshugrue/trainSpotter#1]
/Users/jpshugrue/Documents/projects/trainSpotter/node_modules/protobufjs/src/reader.js:375
            throw Error("invalid wire type " + wireType + " at offset " + this.pos);
            ^

Error: invalid wire type 4 at offset 1
    at Error (native)
    at BufferReader.Reader.skipType (/Users/jpshugrue/Documents/projects/trainSpotter/node_modules/protobufjs/src/reader.js:375:19)
    at Function.decode (/Users/jpshugrue/Documents/projects/trainSpotter/gtfs/gtfs-realtime.js:116:28)
    at Request.request [as _callback] (/Users/jpshugrue/Documents/projects/trainSpotter/server/trains.js:14:70)
    at Request.self.callback (/Users/jpshugrue/Documents/projects/trainSpotter/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/jpshugrue/Documents/projects/trainSpotter/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)

**Comment by jpshugrue** [comment]
Solved: Caused by bad HTTP call to MTA datastream which often corrupted the buffer. Proper use of buffer fixed with built in HTTP fixed

**Comment by VGoose** [comment]
Can you share your fix?
